// Tailored cover letter — structured. Generated by generate-cover-letter,
// consumed by render-cover-letter-pdf. Persisted to output/<source>/<slug>/<slug>-cover_letter.json.

export type CoverLetterContact = {
  email: string | null;
  phone: string | null;
  location: string | null;
  linkedinDisplay: string | null;
  portfolioDisplay: string | null;
};

export type TailoredCoverLetter = {
  name: string;
  contact: CoverLetterContact;
  /** ISO date or pretty date — rendered as-is. */
  date: string;
  /** Recipient block, line-broken. e.g. "Hiring Team\nAcme Pty Ltd". */
  recipientBlock: string;
  /** "Dear Hiring Team," or similar. */
  salutation: string;
  /** Exactly 3 paragraphs in the recommended format. */
  bodyParagraphs: string[];
  /** "Sincerely," / "Kind regards," etc. */
  closing: string;
};
