// Tailored-resume schema. Generated by generate-resume, consumed by
// render-resume-pdf. Persisted to disk at output/<source>/<slug>/<slug>-resume.json.

export type TailoredContact = {
  email: string | null;
  phone: string | null;
  location: string | null;
  linkedinUrl: string | null;
  linkedinDisplay: string | null;
  portfolioUrl: string | null;
  portfolioDisplay: string | null;
  github: string | null;
};

export type TailoredExperience = {
  company: string;
  role: string;
  period: string;
  location: string | null;
  /** May contain inline **bold** for keyword emphasis. */
  highlights: string[];
};

export type TailoredProject = {
  name: string;
  /** Short tag like "Backend / Platform" or "AI / ML". Optional. */
  badge: string | null;
  description: string;
  /** May contain inline **bold**. */
  highlights: string[];
  technologies: string[];
};

export type TailoredEducation = {
  degree: string;
  institution: string;
  period: string;
  details: string | null;
};

export type TailoredSkillGroup = {
  category: string;
  items: string[];
};

export type TailoredResume = {
  name: string;
  contact: TailoredContact;
  /** Re-targeted summary for this specific job. */
  summary: string;
  /** Tag chips below the summary. */
  competencies: string[];
  experience: TailoredExperience[];
  projects: TailoredProject[];
  education: TailoredEducation[];
  certifications: string[];
  skills: TailoredSkillGroup[];
};
